### ISSUE TITLE
Don't override Object#send

### ISSUE THREAD

**Issue by andrhamm** [MightySignal/slackiq#1]
On the Readme I see you've made a method called `send` on the Slackiq class and this could cause unexpected errors since Object#send is a commonly used method in Ruby.

**Comment by jasonlew** [comment]
Thanks for catching that. It's changed from `send` to `message` in version 1.1.1.

**Comment by andrhamm** [comment]
Ok, not to pester but expressive method names are a big help for clients of any library. "`message`" doesn't really tell me what the method is going to do. Consider something like "`slack`" (in our office "Slack" is used as a verb) which would tell me it is going to Slack the message to a chatroom, or "`send_webhook`" or "`post_webook`". You get the idea. Sorry for not putting this in the original issue. 

On another note, it would be good to have some docs about how you think this library should be used with non-Pro Sidekiq. I see in one of your commits you removed "Pro" from the description so that leads me to believe you plan on supporting non-Pro Sidekiq but it looks like the code expects `Batch` support, which is Pro only. Thanks
